import type { NextPage } from 'next'
import { useState } from 'react'
import { Header } from '../components/header'
import { useSearch } from '../hooks/useSearch'
import PhotoList from '../components/photolist'
import Head from 'next/head'

const Home: NextPage = () => {
  const [searchQuery, setSearchQuery] = useState<string>('')
  const { data, refetch } = useSearch(searchQuery)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header setSearchQuery={setSearchQuery} refetch={refetch} />
      <PhotoList data={data} />
    </div>
  )
}

export default Home
