import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from '../components/header'
import PhotoList from '../components/photolist'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <PhotoList />
    </div>
  )
}

export default Home
